server:
  port: 9003
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/echarts
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: cloud-nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.pkm.pkmdb.object
management:
  endpoints:
    web:
      exposure:
        include: '*'  #监控